on: [push]

jobs:
  dbt_build:
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\\\"commands\\\": [\\\"--version\\\"]}"
      DATA_WRANGLER: awswrangler-layer-2.9.0-py3.8
      JSONREF: jsonref-0.2

    steps:
    - uses: actions/checkout@v2
    
    - name: zip and push lambdas
      id: zip
      run: |
        lambdas=$(ls infrastructure/lambdas) 
        for lambda in $lambdas; do
            if test -f "infrastructure/lambdas/$lambda/requirements.txt"; then
              pip install -r infrastructure/lambdas/$lambda/requirements.txt --target infrastructure/lambdas/$lambda/
              # Remove boto packages since we're deploying to lambda anyway
              find . -type d -name "infrastructure/lambdas/$lambda/boto*" -exec rm -r {} +
            fi
            ls infrastructure/lambdas/$lambda/

            echo "zipping lambda $lambda"
            7z a -tzip "$lambda" "./infrastructure/lambdas/$lambda/*"
          done
