on: 
  pull_request:
    types: [closed]
    branches:
      - "main"
    paths:
      - "infrastructure/lambdas/**"
      - ".github/workflows/dev.yml"

jobs:
  dbt_build:
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\\\"commands\\\": [\\\"--version\\\"]}"
      DATA_WRANGLER: awswrangler-layer-2.9.0-py3.8
      JSONREF: jsonref-0.2

    steps:
    - uses: actions/checkout@v2
    
    - name: Run Checkov action
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: infrastructure/
        quiet: true # optional: display only failed checks
        soft_fail: true # optional: do not return an error code if there are failed checks
        output_format: github_failed_only # optional: the output format, one of: cli, json, junitxml, github_failed_only
        download_external_modules: true # optional: download external terraform modules from public git repositories and terraform registry
