on: [push]

jobs:
  dbt_build:
    strategy:
      matrix:
        lambdas: ["lambda1", "lambda2"]
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\\\"commands\\\": [\\\"--version\\\"]}"

    steps:
    - uses: actions/checkout@v2
    
    - name: zip and push lambdas
      run: |
        lambdas=$(ls infrastructure/lambdas) 
        for lambda in $lambdas; do
          echo "zipping lambda $lambda"
          7z a -tzip "$lambda" "./infrastructure/modules/service/lambdas/$lambda/*"
          echo "aws s3 cp '$lambda.zip' 'lambdas/$lambda.zip"
        done
