on: [push]

jobs:
  dbt_build:
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\\\"commands\\\": [\\\"--version\\\"]}"
      DATA_WRANGLER: awswrangler-layer-2.9.0-py3.8
      JSONREF: jsonref-0.2

    steps:
    - uses: actions/checkout@v2
    
    - name: zip and push lambdas
      id: zip
      run: |
        s3_bucket=$(echo "${{ secrets.S3_BUCKET_URI }}" | sed 's/^s3:\/\///g')
        echo "$s3_bucket"
