on: [push]

jobs:
  dbt_build:
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\\\"commands\\\": [\\\"--version\\\"]}"
      DATA_WRANGLER: awswrangler-layer-2.9.0-py3.8
      JSONREF: jsonref-0.2

    steps:
    - uses: actions/checkout@v2
    
    - name: install checkov
      run: pip3 install checkov
    
    - name: run checkov
      run: checkov -d infrastructure --quiet --compact --soft-fail
      
    - name: warning
      run: echo "::warning file=app.js,line=1,col=5::Missing semicolon"
