on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: 
      name: Dev

    steps:
    - uses: actions/checkout@v2
    - name: install dbt
      run: pip install dbt==0.19.1
    - name: version check dbt
      run: dbt --version
    - name: set schema
      run: echo "DBT_SCHEMA='${GITHUB_REF##*/} ${{ secrets.DBT_SCHEMA }}'" >> $GITHUB_ENV
    - name: schema
      run: echo ${{ env.DBT_SCHEMA }} 
