on: [push]

jobs:
  dbt_build:
    strategy:
      matrix:
        lambdas: ["lambda1", "lambda2"]
    runs-on: ubuntu-20.04
    environment: 
      name: Dev
      
    env:
      LAMBDA: ${{ matrix.lambdas }}
      COMMAND: "{\"commands\": [\"--version\"]}"

    steps:
    - uses: actions/checkout@v2
    
    - name: lambda
      run: echo $( ${{ env.COMMAND }} | jq -aRs )

