on: 
  push:
    branches-ignore:
      - "default"

jobs:
  build_dev:
    if: ${{ github.base_ref != 'main' }}
    runs-on: ubuntu-latest
    environment: 
      name: Dev

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: echo "dev build. head_ref= $GITHUB_HEAD_REF base_ref= $GITHUB_BASE_REF"
      
  build_prod:
    if: ${{ github.base_ref == 'main' }}
    runs-on: ubuntu-latest
    environment: 
      name: Prod

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: echo "prod build. head_ref= $GITHUB_HEAD_REF base_ref= $GITHUB_BASE_REF"
      
