on: 
  push:
    branches-ignore:
      - "default"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Reyzor'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.myOutput }}
        echo "total memory successfully output"
    - name: install dbt
      run: pip install dbt==0.19.1
    - name: version check dbt
      run: dbt --version
    - name: set schema
      run: echo "::set-env name=DBT_SCHEMA::${GITHUB_REF##*/} ${{ secrets.DBT_SCHEMA }}"
    - name: schema
      run: echo ${{ env.DBT_SCHEMA }} 
