on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Reyzor'
    - name: output the memory
      run: |
        echo ${{ steps.hello.outputs.myOutput }}
        echo "total memory successfully output"
    - name: install dbt
      run: pip install dbt
    - name: version check dbt
      run: dbt --version
