on: 
  push:
    branches-ignore:
      - "default"

jobs:
  build_dev:
    if: ${{ !contains(github.event.pull_request.base.ref, "dev") }}
    runs-on: ubuntu-latest
    environment: 
      name: Dev

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: echo "dev build"
      
  build_prod:
    if: ${{ !contains(github.event.pull_request.base.ref, "main") }}
    runs-on: ubuntu-latest
    environment: 
      name: Prod

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: echo "prod build"
      
